spring:
  artemis:
    mode: embedded
    # Optional but recommended: explicitly create your test queue.
    # Replace the value below with the EXACT string value of your constant
    # CapitalRaiseListenerService.IN_QUEUE (e.g. "capital.raise.queue")
    embedded:
      queues: CapitalRaiseQueue

  jms:
    listener:
      auto-startup: true
      acknowledge-mode: auto
